# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff597f16d5fb285c9aaa49b7ad14e7f552ab2b1fb2a9688c20a606d2d80aca2d68e5c240ba15ab84051038e829cc7f50ae4d42f324aac565507d829301385aae

test:
  secret_key_base: 53fc69d361a48ba3b5af93b9d17192992a3d2fbfba8942624efb0e5500361e7b7069e83b21cd2d909e44d8f4a7916f461a559f961d889764befadc8870d2f9f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
